apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/cp-20/web-comic-library-web
    newTag: bdb85504d1de4d42e2be08355316abd25c7538bd
  - name: ghcr.io/cp-20/web-comic-library-api
    newTag: bdb85504d1de4d42e2be08355316abd25c7538bd
  - name: ghcr.io/cp-20/web-comic-library-worker
    newTag: bdb85504d1de4d42e2be08355316abd25c7538bd
