apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  template:
    spec:
      source:
        path: '{{.path.basename}}/overlays/production'
