apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traq-ing

spec:
  entryPoints:
    - websecure
  tls:
    secretName: traq-ing-tls
  routes:
    - kind: Rule
      match: Host(`traqing.local.cp20.dev`)
      services:
        - kind: Service
          namespace: traqing
          name: traq-ing-client
          port: 80
          scheme: http
          strategy: RoundRobin
          weight: 1
