apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-comic-library-base-backup
  namespace: postgresql
  labels:
    app.kubernetes.io/part-of: web-comic-library
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  schedule: '0 3 * * 0'
  successfulJobsHistoryLimit: 1
  timeZone: Asia/Tokyo
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/part-of: web-comic-library
    spec:
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          securityContext:
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: backup
              image: ghcr.io/cp-20/web-comic-library-database:latest
              command:
                - /bin/sh
                - -ceu
                - |
                  wal-g backup-push
                  wal-g delete retain FULL 5 --use-sentinel-time --confirm
              envFrom:
                - secretRef:
                    name: web-comic-library-backup
              env:
                - name: AWS_ENDPOINT
                  value: https://a43ad580a36eae6c78e37ef19e4580c3.r2.cloudflarestorage.com
                - name: AWS_REGION
                  value: auto
                - name: AWS_S3_FORCE_PATH_STYLE
                  value: 'true'
                - name: PGDATABASE
                  value: postgres
                - name: PGHOST
                  value: postgresql-headless.postgresql.svc.cluster.local
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-password
                      key: root
                - name: PGUSER
                  value: postgres
                - name: WALG_COMPRESSION_METHOD
                  value: lz4
                - name: WALG_LIBSODIUM_KEY_TRANSFORM
                  value: base64
                - name: WALG_PREVENT_WAL_OVERWRITE
                  value: 'true'
                - name: WALG_S3_PREFIX
                  value: s3://cp20-web-comic-library-backups/postgresql/16
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
