resources:
  - ../../base
  - base-backup-cronjob.yaml

generators:
  - ksops.yaml

configMapGenerator:
  - name: postgresql-config
    namespace: postgresql
    behavior: merge
    files:
      - config/pg_hba.conf

patches:
  - path: backup-patch.yaml

images:
  - name: ghcr.io/cp-20/web-comic-library-database
    newTag: 226dcd23c07592570d5e01b69600d3a5fad09185
