apiVersion: v1
kind: Secret
metadata:
    name: web-comic-library-database
    namespace: web-comic-library
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
        argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:nRyl+82gXa9t008Uu8L6IxVWkK/fzBvEvlfN2G0eNrP15CofIapoOWlYJ3grfMHuvVMhInvNMIBxHglD2KU9nQ==,iv:EmMnTVDrOVuYJ4jpz6oi+0hh6Rt9/N1XEhIZ19gA7is=,tag:GCxE3VToWbqVQ0DRemBtgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufem39g0w04wvc48n3q54ck26japsp9pe6fhykyw73q9u95xf5sqyv3u7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NENFdnVYWXNIQzY3ZzFP
            NFhXQ3IvaldwZGM2ZW5lRTlJd21uQVlacWwwClVQMFJ2cU1MbmJFTmcweExpc08y
            RWsyOEQ1UDFEbDFyTUdreHFZODU0SHMKLS0tIFBCWGNkeE5JbEJqUVhncVRvR2NG
            eVdzQnMvcWhQNXFtMCtjVmh1aHZSaDAKLX0aodtcqAG58EGvEmb41RwW+px4xaE+
            M3Uyc8E1IllAHdkuPzkOMJHGl7BFBOcgyD5DKRrq6BImQVFJMCDOzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T13:32:07Z"
    mac: ENC[AES256_GCM,data:Q7+68nZrFBIN6ZD7crlc4XdnYUqUryi4lXbLwpdJyntGIzOzvhXpQDtBKSYib/VOqu2E1Rr29jLBJaZ7ROLRhufPenXnZmpg8sxnt1us/JbKNrCL8et7coT4mw0rxEqbsZ4wttpbA4WuD/XRerRbqVTLTN3I4Hk9b2h6Qlo7zDU=,iv:CJz4xVgDrm//SCkoxp/oVLhRzIEAjX3mKyugdffhrg0=,tag:3ezX1E/o1uX/fKu+pYnaGg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
