apiVersion: v1
kind: Secret
metadata:
    name: web-comic-library-database
    namespace: postgresql
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
        argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:XNNLjSs2J1iV+SE/0XIPkiFGj5iaip6OLHYwa2erGzQwt/5zpbXIRIaICZn7JsZdUffiBH8cg986+NdQfy/Ujw==,iv:ZDZgTf6iPh7wvCJOS8FjQWPJsJklvCF1GShnxqQ1qUw=,tag:32/pSnknklPBcVFYconZfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufem39g0w04wvc48n3q54ck26japsp9pe6fhykyw73q9u95xf5sqyv3u7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UmlvVk43dm9hS0I4c3Zk
            Z0YwRHhxU0VOQzV4SmwzZ0RDUWhVVFR2MGlvCmNmMEJrM2QwRWlEQ2RycTRwbEpy
            NE5VMHBIOXNpTW1vaU5tZy93akphUnMKLS0tIGhPdmJsM0Ftc0FpazFaNDIzaVlh
            bjZvVnhQNCtIV01uMUY5Zkx1STlhSFUKlkNzZwGFV7x/osz1eWwVU3uwejDSuyKl
            J1f2cxT0mrvlgA6XURUKaIrwhJFs6JD0oUu+EWBlmRnnV+PXXyAsvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T13:32:07Z"
    mac: ENC[AES256_GCM,data:nQnzG6Uh0nCvwQTN6Yx2mdCSiuyAE4mEtq6HigVk5Wr7y7WnGlOZVKXMt0zLaF4v1tCCUXbLhJmK3joeFwa4D4RvxsAeylOrbyewv8FXSHyHdoZ1v6OKP43F0BmzZ9ytukY3H3cVa5xj1sDgGsQayakJNqQxmbJ2lTaBY4A8gzI=,iv:WNs0WTzEB03lZYk5xucNNi0i9erFGZ0anwfCqUI3bzg=,tag:bP/EXiE1eiKz3HNwOZPYNw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
