version: '3'

tasks:
  default:
    cmds:
      - echo "Tasks:\n  build\n  test\n  clean"
  encrypt-secret:
    cmds:
      - sops --encrypt --config .sops.yaml --in-place {{.CLI_ARGS}}
  edit-secret:
    cmds:
      - sops --config .sops.yaml --in-place {{.CLI_ARGS}}
  argocd-secret:
    cmds:
      - kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode && echo
  argocd-port-forward:
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8124:443
