apiVersion: v1
kind: Secret
metadata:
    name: web-comic-library-backup
    namespace: postgresql
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:hgK0yEmwrXNxKhhpKhwgoSbofBn2lrs1wIuXWUa+neQ=,iv:v0R2ZJRoTZU47NmSRYkpoHjwi8Uojc1LPSmaADpQFww=,tag:NMOxy14Ozl0GdraOA/Jmsw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QIn2k+rt519tgAbNayrfaZJFVxaHLtaLIyWPnQizY7y2le9kG+ZJ9Eb5SLHx2g877hDcmj3lLNApv+xjUKO1rw==,iv:TFFyrtjdRE807maUgR0qhSGg72LUG9BAm0EI/XmcTwI=,tag:GKuxGHnT8gZuLIzzNkZr0A==,type:str]
    WALG_LIBSODIUM_KEY: ENC[AES256_GCM,data:EW+s50TFP2Tt1MFO/XC87Fvx54Xi/sSUFmkhhN3rxtkxq5Obgo3+GLIvqHU=,iv:yCu8wP+veC9oPmhGotT9CG58Xm6BeEDDJjLPp3Y6P88=,tag:ABCrQKjGbWA8gysiZQgEXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufem39g0w04wvc48n3q54ck26japsp9pe6fhykyw73q9u95xf5sqyv3u7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UWpQNDljSnd2RGhqVmpB
            WHh0QXcySDhiYzE1UFozMnFNN3VicHpUWXdFCnRob2p1N0xEaEs3Mzd1RUJnWERP
            RGxWZ1k3QjFicmRnNEtGT3k0dloxak0KLS0tIHVZcFRvZm9VYUc1WmZJakhuOC96
            alc4YWdybGZhanMxVGVpNjZHS0ExUGsK5sQUnwkcE6138fYaU/imFH7TZAWBwAWT
            BBNg5udZdpndV7lIDbu/+QfNP9eR56mZF+C+oRMIlxlEnCTgIlvQaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T15:34:07Z"
    mac: ENC[AES256_GCM,data:tz+kw6bqGdE3AJesuivocBdQofLfbdCBjmfiiPtpU/1N7+Y34bWsPYIKhuvI8ayJ/rIagzMo8ZRsl5OmKo7njMjU7hHSk/JUCmSmEgefw87+8DNVHpUTzfhLBfvPyfOpB0rx8/3Si7L+E9bv7HQd3SZWsCSTpm3IcalgP0oTwgU=,iv:LGDGhZ55TkiqAKBkgRYCqDZngb+qU4wMlcxPC3I0/I4=,tag:7Ou+DtWvJpwUJZDTXwyBgA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
