apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: postgresql
spec:
  serviceName: postgresql-headless
  selector:
    matchLabels:
      app: postgresql
  template:
    spec:
      containers:
        - name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pg_hba.conf
              name: pg-hba-conf
              subPath: pg_hba.conf
      volumes:
        - name: pg-hba-conf
          configMap:
            name: pg-hba-conf
