apiVersion: v1
kind: Secret
metadata:
    name: traq-ing-key
    namespace: traq-ing
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    traq_auth_client_id: ENC[AES256_GCM,data:lIrSAVRZ1G5gK9rha0xd/d95ko8UTPT7VfbIKOE9RsdJy5HM,iv:rLuGVwotx99yGN3VsdGyunM96m9ChiDpin1Ctf5wjzw=,tag:Xarx0gkHSpMY/9C7sRB80Q==,type:str]
    traq_token: ENC[AES256_GCM,data:FnSc9WwhDbQoqrheuLQsb/+Ik76uos3jn5LACNgp8cQ0iANk,iv:7VsDzbmPKpl5n2aoWG6gAIDVuzg+KxITwCHkMHEl2GQ=,tag:894ygjdU6xhPc2tMsbWO1Q==,type:str]
    database_password: ENC[AES256_GCM,data:eqKB/BpFb/g4qiiqLo/bEWsiAQ==,iv:W/CTrFbmlOyuF/ZoARih48ipkGsu5dwhEE9sN7Vu6pM=,tag:45ONAr13aKcJEULiBSOx7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufem39g0w04wvc48n3q54ck26japsp9pe6fhykyw73q9u95xf5sqyv3u7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNVBTenVHM25KeGFrSGJ0
            aSt4Zmw0WUNyUWkrd013K3lyVk9NakdMZUFNCkI3end3L1JQQzg2SDBVYWJXVTl2
            Nkg1aVp3V1pFenR2WTZYN2FsRVVyRUEKLS0tIEtUdjJXOGZrdFNwRFpFRnZrWW5N
            ZjNIZmg4N3E0Tmtab1VQdVBOdnF4UU0KKqXAM1qbwImWZFUD8TP4u0YjnON7CERO
            WM5PXAsw2cZ/sVz5Y+xVN9YyElLmZ95OVVTrdB3YWnaoMqxCLbbzpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T13:40:13Z"
    mac: ENC[AES256_GCM,data:PAytYtICM2XgnUvaax7DyaVxvaSy56AgpjvSQGxhUUg1dOX4W8f8nNQ2taiGQle9XZA6zsBYI0GovYVsKDiQsn9cn/Kz8AVmGfnnly7zh4rk6dUZyzkkLd9fBR91M/XMvESBc5wGs/uLrynRFKZddzW27R6qKO53LOIWFAghEzU=,iv:4sfCbmiWeoJsEfHcSVCGspLh1/2SnRdoDOwt+Usac1k=,tag:YK0KLaNKnKZdcEQ0VRMCSw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
