apiVersion: v1
kind: Secret
metadata:
    name: traq-ing-key
    namespace: traq-ing
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    traq_auth_client_id_dev: ENC[AES256_GCM,data:yozMPQGwkZfeKc2wXp5yGKXFuDbP59GPJ7qUQ0E4NGK/hIpz,iv:O1uKys1J9VVOl/9ZyVgj6tev+OIMoICNoGYnfTnG4uY=,tag:ZOg8OJjzxF6rE6CyG7msIA==,type:str]
    traq_auth_client_id_prod: ENC[AES256_GCM,data:ASpDL4uljqcOi904SmMqrguEVgddrynkGbwHjCk5Ouh+scil,iv:bm6U++K4TWzzYbJS670fVCS0ybYCDXcGf9V3shk4uGg=,tag:mZmifhygXXOJ+THwHN2fTw==,type:str]
    traq_token: ENC[AES256_GCM,data:FnSc9WwhDbQoqrheuLQsb/+Ik76uos3jn5LACNgp8cQ0iANk,iv:7VsDzbmPKpl5n2aoWG6gAIDVuzg+KxITwCHkMHEl2GQ=,tag:894ygjdU6xhPc2tMsbWO1Q==,type:str]
    database_password: ENC[AES256_GCM,data:eqKB/BpFb/g4qiiqLo/bEWsiAQ==,iv:W/CTrFbmlOyuF/ZoARih48ipkGsu5dwhEE9sN7Vu6pM=,tag:45ONAr13aKcJEULiBSOx7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufem39g0w04wvc48n3q54ck26japsp9pe6fhykyw73q9u95xf5sqyv3u7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNVBTenVHM25KeGFrSGJ0
            aSt4Zmw0WUNyUWkrd013K3lyVk9NakdMZUFNCkI3end3L1JQQzg2SDBVYWJXVTl2
            Nkg1aVp3V1pFenR2WTZYN2FsRVVyRUEKLS0tIEtUdjJXOGZrdFNwRFpFRnZrWW5N
            ZjNIZmg4N3E0Tmtab1VQdVBOdnF4UU0KKqXAM1qbwImWZFUD8TP4u0YjnON7CERO
            WM5PXAsw2cZ/sVz5Y+xVN9YyElLmZ95OVVTrdB3YWnaoMqxCLbbzpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T13:08:53Z"
    mac: ENC[AES256_GCM,data:EBdM9XGR31Qyu5ZzCv+p6GdKQ1M+FVL4RpqPqYclthvtK5GeJeMX9bONOKJ0tHfvLZnWn5vElZrqRAF/Z0llC5x+q3KIPUasVhSmNIMRyarNTNx1sI68/HMix8cw957XZIZ6Gxl50PE1UFMLIY9WzgtwJKcMNDCcR7EutA9JCxI=,iv:A+83SPIcW2LQA9DvVe1/slmI0g5iCQhVpBfZZdCt4l0=,tag:H3N5SzGoSW23AjGgxyZsPg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
