apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls

spec:
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: argocd-server-tls
  duration: 2160h0m0s # 90d
  renewBefore: 720h0m0s # 30d
  dnsNames:
    - cd.local.cp20.dev
