apiVersion: v1
kind: Secret
metadata:
    name: web-comic-library-operations
    namespace: web-comic-library
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zX3/uJlr/0M1ekVOigsxk75Cj40S4b+sQN1MmdcWADw=,iv:fDP77FxyklCitJMvZh5YFC9FP6HtEJsC0gPOTb8nT5k=,tag:ok4Ng9JYah48gBsWpTsjEQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hFYuPll1WTu4Fk5XEIbkmEbIcj9GWKoHOojYJ0+BQt6KwnhPgQfFIPlqF1X42O1DzQWHmSFvrpc2vz14kJdOGQ==,iv:mqizO14kNBx+N00JoNTZ2n0V3CPr2hcZxldXuwqcQF8=,tag:+E6p/6O7IlN35ngHoNZJog==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:B+AnEjd39IIsHm5FaujnZiciBaL3iNEk1na8sDpPae/X/0gsefWxPxRhZwQ1ZI4IZHTy6l1mlDSy4nSMEdSKqPNCgWadgNtNR7OF30rRmxqGd2fmBbHzk9jzdrJziFA=,iv:OL72ywKYtFJ6IalyIOTZziZhe55By+dFvJptw7wOqcU=,tag:+DImhsq3zYqOp6djuxYj2A==,type:str]
    WALG_LIBSODIUM_KEY: ENC[AES256_GCM,data:UOD1alFp8y8E7QYN+IOJKf3Z15nWNyFZxWTha/UJXJGehAW1iPS+ITd1+wg=,iv:OHuppfQmvW58HrFIhg4WW/7J+QSwt8Ompg9h0PunIHg=,tag:nMrq4c9NncMTjvWVqx57yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufem39g0w04wvc48n3q54ck26japsp9pe6fhykyw73q9u95xf5sqyv3u7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR3c2K1UvNGZaVXVZeFdn
            VnVWTnJVek5SRVFnTXhWVnNla1RFWGd1TGdvCm91U0JsVVMzV0Z0eWN4SnNXa2tm
            R1NLNmFZUWpvUEk3WW1xZllWYWoxWUUKLS0tIFFJUXh5SjdiY2lkaUJSZjZPZXRw
            cGRZQmwvV1JaVThZNHB2QkRUZjAyMGMKnqNWyxbdI2k2LyhrkPbcDDNETpraVZPL
            RPCMX1PoHonJPiR5Uc0s9isnYUkeh01Ssg0amr47mgSWaJ4kjxT4XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T15:25:48Z"
    mac: ENC[AES256_GCM,data:vo8B/HHZf2xSr9cWsnvSuAHUdUAOlEhmR1/SPo9lJ0M4qBTbMW+b/kFOxlv2jxslLjQ7dYLPz9XHVJA+rX1eLXq3IcMIbVinneupC5AkNdWscq/14lszvYth6GIuX6ToN5cIYb9zPRw+tnPB/76Kg6pDrLn6CBCeUeWSHs1RDdY=,iv:99RK+tyGrElgqdPhqUezVtiqSZFxW7NsnFsaWoN1oLg=,tag:nDJ4zH6xmXGU64SROjWPmA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
