apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer

spec:
  acme:
    email: n.naoki.1587@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              # Referenced in kustomize-config.yaml for hash suffix substitution
              name: dns-solver
              key: key
