apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # renovate:github-url
  - https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml
  - cluster-issuer.yaml

generators:
  - ksops.yaml

configurations:
  - kustomize-config.yaml
