# For Secret name with hash suffix substitution
nameReference:
  - kind: Secret
    fieldSpecs:
      - kind: WorkflowTemplate
        path: spec/template/spec/containers/env/valueFrom/secretKeyRef/name
