apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - stateful-set.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: init-script-config
    files:
      - config/init.sh

generators:
  - ksops.yaml
