apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
