apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: postgresql
spec:
  serviceName: postgresql-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          command:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: root
            - name: POSTGRES_PASSWORD_TRAQING
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: traqing
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 10
                    psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'traqing'" | grep -q 1 || psql -U postgres -c "CREATE DATABASE traqing;"
                    psql -U postgres -tc "SELECT 1 FROM pg_roles WHERE rolname = 'traqing'" | grep -q 1 || psql -U postgres -c "CREATE USER traqing WITH PASSWORD '${POSTGRES_PASSWORD_TRAQING}';"
                    psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE traqing TO traqing;"
                    psql -U postgres -c "ALTER DATABASE traqing OWNER TO traqing;"
          resources:
            limits:
              memory: '2048Mi'
              cpu: '4000m'
            requests:
              memory: '512Mi'
              cpu: '500m'
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
        - name: postgresql-config
          configMap:
            name: postgresql-config
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 256Mi
