apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ing-server
  namespace: traq-ing
  labels:
    app: traq-ing-server
spec:
  tempalte:
    spec:
      containers:
        - name: traq-ing-server
          env:
            - name: TRAQ_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traq-ing-key
                  key: traq_auth_client_id_dev
