apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: postgresql-ingress-route
  namespace: postgresql

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`postgresql.local.cp20.dev`)
      services:
        - kind: Service
          name: postgresql-headless
          port: 5432
          scheme: tcp
          strategy: RoundRobin
          weight: 1
