apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgresql-ingress-route
  namespace: postgresql

spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: postgresql-headless
          namespace: postgresql
          port: 5432
