apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-hba-conf
  namespace: postgresql
  annotations:
    kustomize.config.k8s.io/needs-hash: 'true'

data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    traqing         traqing         0.0.0.0/0               scram-sha-256
