apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server-deployment.yaml
  - server-service.yaml
  - client-deployment.yaml
  - service-client.yaml
  - update-statistics-job.yaml
  - update-messages-job.yaml

generators:
  - ksops.yaml
