apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-route.yaml
  - server-deployment.yaml
  - server-service.yaml
  - client-deployment.yaml

generators:
  - ksops.yaml

configurations:
  - kustomize-config.yaml
