apiVersion: apps/v1
kind: Deployment
metadata:
  name: traq-ing-server
  namespace: traq-ing
  labels:
    app: traq-ing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traq-ing-server
  template:
    metadata:
      labels:
        app: traq-ing-server
    spec:
      containers:
        - name: traq-ing-server
          image: ghcr.io/cp-20/traq-ing-server:1.1.12
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: '2Gi'
              cpu: '2000m'
            requests:
              memory: '256Mi'
              cpu: '250m'
          env:
            - name: TRAQ_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: traq-ing-key
                  key: traq_auth_client_id_prod
            - name: TRAQ_TOKEN
              valueFrom:
                secretKeyRef:
                  name: traq-ing-key
                  key: traq_token
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: traq-ing-key
                  key: secret_key
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: traq-ing-key
                  key: database_password
            - name: DATABASE_URL
              value: postgressql://traqing:$(DATABASE_PASSWORD)@postgresql-headless.postgresql.svc.cluster.local:5432/traqing
