apiVersion: batch/v1
kind: CronJob
metadata:
  name: traq-ing-update-messages-job
  namespace: traq-ing
spec:
  # 毎時0分に実行
  schedule: '0 * * * *'
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: traq-ing-update-messages
              image: ghcr.io/cp-20/traq-ing-server:latest
              command: ['bun', 'run', 'run:update-messages']
              env:
                - name: TRAQ_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: traq_token
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: database_password
                - name: DATABASE_URL
                  value: postgressql://traqing:$(DATABASE_PASSWORD)@postgresql-headless.postgresql.svc.cluster.local:5432/traqing
      parallelism: 1
