apiVersion: batch/v1
kind: CronJob
metadata:
  name: traq-ing-update-messages-job
  namespace: traq-ing
spec:
  # 毎時0分に実行
  schedule: '0 * * * *'
  timeZone: Asia/Tokyo
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          initContainers:
            - name: check-update-all-messages-job
              image: bitnami/kubectl:latest@sha256:9081a6f83f4febf47369fc46b6f0f7683c7db243df5b43fc9defe51b0471a950
              command:
                - /bin/sh
                - -c
                - |
                  if kubectl get jobs -n traq-ing | grep -q 'traq-ing-update-all-messages-job.*1/1'; then
                    echo "update-all-messages-job is running, exiting."
                    exit 1
                  fi
          containers:
            - name: traq-ing-update-messages
              image: ghcr.io/cp-20/traq-ing-server:1.1.14
              command: ['bun', 'run', 'run:update-messages']
              env:
                - name: TRAQ_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: traq_token
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: secret_key
                - name: SERVER_URL
                  value: http://traq-ing-server.traq-ing.svc.cluster.local:8080
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: database_password
                - name: DATABASE_URL
                  value: postgressql://traqing:$(DATABASE_PASSWORD)@postgresql-headless.postgresql.svc.cluster.local:5432/traqing
