apiVersion: batch/v1
kind: CronJob
metadata:
  name: traq-ing-update-statistics-job
  namespace: traq-ing
spec:
  # 毎日朝4時に実行
  schedule: '0 4 * * *'
  timeZone: Asia/Tokyo
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: traq-ing-update-statistics
              image: ghcr.io/cp-20/traq-ing-server:1.1.22
              command: ['bun', 'run', 'run:update-statistics']
              env:
                - name: TRAQ_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: traq_token
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: secret_key
                - name: SERVER_URL
                  value: http://traq-ing-server.traq-ing.svc.cluster.local:8080
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: traq-ing-key
                      key: database_password
                - name: DATABASE_URL
                  value: postgressql://traqing:$(DATABASE_PASSWORD)@postgresql-headless.postgresql.svc.cluster.local:5432/traqing
