apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - logical-backup-cronjob.yaml
  - worker-metrics-service.yaml

generators:
  - ksops.yaml

patches:
  - path: observability-patch.yaml

images:
  - name: ghcr.io/cp-20/web-comic-library-web
    newTag: 4921bb7acf42b6730f62e5b9e49a807b78b60d83
  - name: ghcr.io/cp-20/web-comic-library-api
    newTag: 4921bb7acf42b6730f62e5b9e49a807b78b60d83
  - name: ghcr.io/cp-20/web-comic-library-worker
    newTag: 4921bb7acf42b6730f62e5b9e49a807b78b60d83
  - name: ghcr.io/cp-20/web-comic-library-database
    newTag: 226dcd23c07592570d5e01b69600d3a5fad09185
