apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - logical-backup-cronjob.yaml
  - worker-metrics-service.yaml

generators:
  - ksops.yaml

patches:
  - path: observability-patch.yaml

images:
  - name: ghcr.io/cp-20/web-comic-library-web
    newTag: 457f2e9b4ff8a49e109ec098ce7f07503dd6299a
  - name: ghcr.io/cp-20/web-comic-library-api
    newTag: 457f2e9b4ff8a49e109ec098ce7f07503dd6299a
  - name: ghcr.io/cp-20/web-comic-library-worker
    newTag: 457f2e9b4ff8a49e109ec098ce7f07503dd6299a
  - name: ghcr.io/cp-20/web-comic-library-database
    newTag: 226dcd23c07592570d5e01b69600d3a5fad09185
