apiVersion: batch/v1
kind: CronJob
metadata:
  name: logical-backup
  namespace: web-comic-library
  labels:
    app.kubernetes.io/part-of: web-comic-library
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  schedule: '30 3 * * *'
  successfulJobsHistoryLimit: 1
  timeZone: Asia/Tokyo
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/part-of: web-comic-library
    spec:
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          securityContext:
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: backup
              image: ghcr.io/cp-20/web-comic-library-database:latest
              command:
                - logical-backup
              envFrom:
                - secretRef:
                    name: web-comic-library-operations
              env:
                - name: AWS_ENDPOINT
                  value: https://a43ad580a36eae6c78e37ef19e4580c3.r2.cloudflarestorage.com
                - name: AWS_REGION
                  value: auto
                - name: AWS_S3_FORCE_PATH_STYLE
                  value: 'true'
                - name: S3_ENABLE_VERSIONING
                  value: disabled
                - name: S3_MAX_RETRIES
                  value: '3'
                - name: PGDATABASE
                  value: web_comic_library
                - name: PGHOST
                  value: postgresql-headless.postgresql.svc.cluster.local
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: web-comic-library-database
                      key: password
                - name: PGUSER
                  value: web_comic_library
                - name: WALG_COMPRESSION_METHOD
                  value: lz4
                - name: WALG_LIBSODIUM_KEY_TRANSFORM
                  value: base64
                - name: WALG_S3_PREFIX
                  value: s3://cp20-web-comic-library-backups
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
