apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web-comic-library
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: web-comic-library-operations
                  key: SENTRY_DSN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: web-comic-library
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: web-comic-library-operations
                  key: SENTRY_DSN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: web-comic-library
spec:
  template:
    spec:
      containers:
        - name: worker
          ports:
            - name: metrics
              containerPort: 3002
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
