apiVersion: v1
kind: Service
metadata:
  name: worker-metrics
  namespace: web-comic-library
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: metrics
      port: 3002
      targetPort: metrics
