apiVersion: v1
kind: Secret
metadata:
    name: monitoring-alerts
    namespace: monitoring
type: Opaque
stringData:
    discord-webhook: ENC[AES256_GCM,data:xpppBnp++c5IjjdB2++L9bSbA3PlQQ6ULz4xJv98vVb6ZIhXgDUVTKyK+0sVGVfcd2pGGkCZtD0IWivG40+1a6BtDscP4NkOUfxCowqX+Ljl7reziDp8/Cbek6GRiGp+cAxmmSylNFh8M8py/5wfEXxH9DPw1/kWeA==,iv:V7gvqQSU643IXCeDah3G2Zxayxr3MWW73TOSmnZaEsw=,tag:uAKlW6wa6C0HYnjE5Fc5Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufem39g0w04wvc48n3q54ck26japsp9pe6fhykyw73q9u95xf5sqyv3u7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK0ZES1hoeVpnY3cxK0pC
            eW05Y1BNdlZGNk1jdlJldm5IOTVwZkdaN3hvCnUzZllkSm14MDZTd3pzOFd6N25M
            aHJ6V0ZHeG1FU2FjTE1FMVlUcWI1a00KLS0tIEk1SFlkcXV6OXNiNWpGWTF5UGdl
            NkZhMUdoUHd1VWQ2Q2dhb3JRc2NWeDQKEvJnsRDWl4NJ5w+R3+PTrC/ZgGqqFMr9
            Nqt03pwvpIDC2jmPkDZfTFkBIohyTlnvx/h12GOyToTrz/78Nlfqlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T16:00:45Z"
    mac: ENC[AES256_GCM,data:K2QnwqEit0VM3tl0JMfkHmxzCjFf677+v8AHfz1U2L/BYWDBpDXOVwrbcMNxnAWWy7M69kSYDW1shEs15A+o5VmGrUeiK2/vQ3mQax3SEFWPR32DJ9fnH7WjtCkzCIHip4Y8h9YLnnlt9Kmvod5uSGrtMChl+/dL1h9HzDgbmTE=,iv:hpvoocV+nIppuFjXND9zHMKnpJR44+oDkgvu8eKWwoY=,tag:4EaWarMleo5pShrxM1UAeg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
